name: Test Github action

on:
  push:
    branches:
      - master

jobs:
  echo:
    name: Do somethings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Echo hello world
        run: echo "Hello world!"
        shell: bash
